#ifndef CONFIG_H_
#define CONFIG_H_

#define DISPLAY_TYOE_SIMUL_ADAFRUIT false
#define DISPLAY_TYPE_ST7335_ADAFRUIT false
#define DISPLAY_TYPE_SIMIL_CUSTOM false
#define DISPLAY_TYPE_ST7335_CUSTOM true

#define USER_INPUT_SIMUL false

#define I2C_SIMUL_MEMORY false

#define SPI_DEFAULT_FREQ 16000000L

#endif /* CONFIG_H_ */
