M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Вт 31 окт 2023 14:25:46
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-31T14:25:46+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.6378Y-2.8346
X4.685Y-3.2677
X4.685Y-4.8819
T0
M30
