M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Пн 24 июл 2023 12:55:09
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-24T12:55:09+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.6102Y-1.8268
X4.7913Y-3.4016
X4.7992Y-4.9646
T0
M30
