#ifndef CONFIG_H_
#define CONFIG_H_

#define UART_ENABLED true
#define SET_DEFAULT_V_I_ON_START false

// C2
#define PIN_LED_OVERLOADED 12
// C3
#define PIN_LED_POWEROUTPUT 13

// A7
#define PIN_POWER_OUTPUT_SENSE_I PIN_PA7
// B4
#define PIN_POWER_OUTPUT_SENSE_V PIN_PB4

// A5
#define PIN_POWER_OUTPUT_IC_FB A5
// B5
#define PIN_POWER_OUTPUT_SHUTDOWN PIN_PB5

#define I2C_SLAVE_ADDRESS 0x33

#endif /* #define CONFIG_H_ */
